name: Deploy Laravel Sail AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (Remote) por SSH con Sail
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/laravel-test
            git pull origin main
            ./vendor/bin/sail down
            ./vendor/bin/sail up -d --build
            ./vendor/bin/sail artisan migrate --force